homepage:
    path:     /
    defaults: { _controller: 'CESPres\Website\Controllers\Index::index' }

nlayer_product_view:
    path:     /nlayer/product/{productId}
    defaults: { _controller: 'CESPres\NLayer\Product\Controllers\ProductController::get' }
    methods:  [GET]

nlayer_product_update:
    path:     /nlayer/product/{productId}
    defaults: { _controller: 'CESPres\NLayer\Product\Controllers\ProductController::post' }
    methods:  [POST]

nlayer_product_create:
    path:     /nlayer/product/{productId}
    defaults: { _controller: 'CESPres\NLayer\Product\Controllers\ProductController::put' }
    methods:  [PUT]

cqrs_product_create:
    path:     /cqrs/product
    defaults: { _controller: 'CESPres\CQRS\Product\Controllers\ProductController::post' }
    methods:  [POST]

cqrs_product_view:
    path:     /cqrs/product/{productId}
    defaults: { _controller: 'CESPres\CQRS\Product\Controllers\ProductController::get' }
    methods:  [GET]

es_product_create:
    path:     /es/product
    defaults: { _controller: 'CESPres\ES\Product\Controllers\ProductController::post' }
    methods:  [POST]

es_product_view:
    path:     /es/product/{productId}
    defaults: { _controller: 'CESPres\ES\Product\Controllers\ProductController::get' }
    methods:  [GET]